export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESSFUL = "ADD_PRODUCT_SUCCESSFUL";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const BEGIN_DOWNLOAD = "BEGIN_DOWNLOAD" 
export const BEGIN_DOWNLOAD_SUCCESSFUL = "BEGIN_DOWNLOAD_SUCCESSFUL" 
export const BEGIN_DOWNLOAD_ERROR = "BEGIN_DOWNLOAD_ERROR" 

export const GET_DELETE_PRODUCT = "GET_DELETE_PRODUCT"
export const DELETE_PRODUCT_SUCCESSFUL = "DELETE_PRODUCT_SUCCESSFUL"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"

export const GET_EDIT_PRODUCT = "GET_EDIT_PRODUCT"
export const GET_EDIT_ERROR = "GET_EDIT_ERROR"

export const SHOW_ALERT = "SHOW_ALERT"
export const SHOW_DELETE ="SHOW_DELETE"